speak_to_grandma="I LOVE YOU GRANDMA"
if speak_to_grandma=="'Hi Nana, how are you?'"
  puts "HUH?! SPEAK UP,SONNY!"
elsif "HI!"
  puts "HUH?! SPEAK UP,SONNY!"
else "WHAT DID YOU EAT TODAY?"
  puts "NO, NOT SINCE 1938!"
else "I LOVE YOU GRANDMA"
  puts "I LOVE YOU TOO PUMPKIN!"
end
